#!/bin/bash

while true
do
    figlet "Parch Linux tweak tool"
    echo "Please select a section:"
    echo "1) Change Emoji package"
    echo "2) Libreoffice Installer"
    echo "3) Change Aur Helper "
    echo "4) Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1)
            echo "Please choose an action for emoji Packages:"
            echo "1) ios"
            echo "2) fluent (microsoft)"
            read -p "Enter your choice: " emoji_choice

            case $emoji_choice in
                1)
                    # remove all packages:
                    sudo pacman -Rds fluent-emojies --noconfirm
                    sudo pacman -Sy parch-emoji-ios --noconfirm
                    ;;
                2)
                    sudo pacman -Rds parch-emoji-ios --noconfirm
                    sudo pacman -Sy fluent-emojies --noconfirm
                    ;;
                *)
                    echo "Invalid choice."
                    ;;
            esac
            ;;
        2)
            sudo pacman -Sy libreoffice-fresh --noconfirm
            cp -r /usr/share/parch/template/libreoffice ~/.config/libreoffice
            ;;
        3)
	    echo "Please choose an action for aur helper:"
            echo "1) yay"
            echo "2) paru (default in parchlinux)"
            read -p "Enter your choice: " aur

            case $aur in
                1)
                    # remove all packages:
                    sudo pacman -Rds paru --noconfirm
                    sudo pacman -Sy yay --noconfirm
                    ;;
                2)
                    sudo pacman -Rds yay --noconfirm
                    sudo pacman -Sy paru --noconfirm
                    ;;
                *)
                    echo "Invalid choice."
                    ;;
            esac
            ;;
        4)
            exit 0
            ;;
        *)
            echo "Invalid choice."
            ;;
    esac

    echo "Done with section $choice."
done

exit 0
